

/* Create Tables */

CREATE TABLE URL_CLIENT
(
	-- Agent와 연동되는 아이디
	CLI_ID VARCHAR2(20) NOT NULL,
	BILL_ID VARCHAR2(20) NOT NULL,
	-- RS 접근 방식은 PS방식으로 1번접속 시도후 안될 경우 2번 RS를 접속한다. 3번설정은 없음
	RS_ID1 VARCHAR2(20) NOT NULL,
	-- RS 접근 방식은 PS방식으로 1번접속 시도후 안될 경우 2번 RS를 접속한다. 3번설정은 없음
	RS_ID2 VARCHAR2(20) NOT NULL,
	SMS_ROUTE_ID VARCHAR2(20) NOT NULL,
	MMS_ROUTE_ID VARCHAR2(20) NOT NULL,
	CLI_NAME VARCHAR2(50) NOT NULL,
	-- 고객사암호;  암호화 SHA512
	CLI_PWD VARCHAR2(200) NOT NULL,
	-- 암호화키;Base64encoding
	CLI_SECU_KEY VARCHAR2(200) NOT NULL,
	-- 사용상태
	-- Y:사용,C:탈퇴,P:사용중지
	USE_STATUS CHAR(1) DEFAULT 'Y' NOT NULL,
	DT_UPDATE VARCHAR2(14),
	DT_REG VARCHAR2(14) NOT NULL,
	-- 발송우선순위;0~9 0:아주낮음 9:아주높음
	PRIORITY NUMBER DEFAULT 1,
	MEMO VARCHAR2(200),
	DT_CONN_SND VARCHAR2(14),
	DT_CONN_RCV VARCHAR2(14),
	-- 코드표 참조
	-- RG:일반,VIP:VIP,RS:재판매,FN:금융,GO:공공,TEST:테스트
	CLI_TYPE VARCHAR2(20),
	-- Y,N
	CHK_SESS_STATUS CHAR(1) DEFAULT 'Y',
	-- 세션체크시간;hh24~hh24
	CHK_SESS_TSECTION VARCHAR2(10) DEFAULT '00~00',
	-- 세션체크구간;분
	CHK_SESS_MIN NUMBER DEFAULT 5,
	CHK_SESS_CNT NUMBER DEFAULT 1,
	-- Y,N
	CHK_IDLE_STATUS CHAR(1) DEFAULT 'N',
	-- IDLE체크시간;hh24~hh24
	CHK_IDLE_TSECTION VARCHAR2(10) DEFAULT '00~00',
	-- 분
	CHK_IDLE_MIN NUMBER DEFAULT 5,
	CHK_IDLE_CNT NUMBER DEFAULT 100,
	-- 코드표 참조
	-- ','로 구분하여 나열한다.
	ALARM_GRP VARCHAR2(200) DEFAULT 'OP,ADMIN',
	-- 발송허용시간;hh24~hh24
	ALLOW_TSECTION VARCHAR2(10) DEFAULT '00~00',
	CPS NUMBER DEFAULT 20,
	-- 코드표 참조
	-- M:일,월건수제한,N:사용하지 않음;미사용
	CHK_CNT_TYPE VARCHAR2(20) DEFAULT 'N',
	PCASH_MAX_D NUMBER DEFAULT 1000,
	PCASH_MAX_M NUMBER DEFAULT 10000,
	PCASH_CUR_D NUMBER,
	PCASH_CUR_M NUMBER,
	-- Y,N
	CHK_WHITE_IP_STATUS CHAR(1) DEFAULT 'Y',
	-- WHITE IP;클래스, 127.0.*.*
	WHITE_IP1 VARCHAR2(30),
	-- WHITE IP;클래스, 127.0.*.*
	WHITE_IP2 VARCHAR2(30),
	-- WHITE IP;클래스, 127.0.*.*
	WHITE_IP3 VARCHAR2(30),
	DUP_CLI_KEY_CNT NUMBER DEFAULT 1000,
	DUP_PHONE_CNT NUMBER DEFAULT 100,
	DUP_PHONE_EXPIRE_MIN NUMBER,
	DUP_PHONE_SKIP_CNT NUMBER,
	OP_NAME VARCHAR2(20),
	OP_PHONE VARCHAR2(20),
	OP_MOBILE VARCHAR2(20),
	OP_EMAIL VARCHAR2(50),
	AM_NAME VARCHAR2(20),
	AM_MOBILE VARCHAR2(20),
	AM_EMAIL VARCHAR2(50),
	PCASH_MAX_ADV NUMBER,
	PCASH_CUR_ADV NUMBER,
	CHK_SND_CNT NUMBER DEFAULT 1000,
	CHK_RPT_CNT NUMBER DEFAULT 10000,
	-- 코드표 참조
	-- 선불:PP, 후불:DP
	PAY_TYPE VARCHAR2(20) DEFAULT 'DP',
	EXP_RPT_HOUR NUMBER DEFAULT 100 NOT NULL,
	EXP_DELIVER_HOUR NUMBER DEFAULT 12 NOT NULL,
	-- 코드표 참조
	CHK_SESS_TYPE VARCHAR2(20),
	MW_URL_DOMAIN VARCHAR2(30) DEFAULT 'urlweb.kr',
	PRIMARY KEY (CLI_ID, BILL_ID)
);


CREATE TABLE URL_CODE
(
	-- 코드표의 CATEGORY 그룹 참조
	CATEGORY VARCHAR2(20) NOT NULL,
	CD VARCHAR2(20) NOT NULL,
	CD_DESC VARCHAR2(100) NOT NULL,
	-- Y,N
	USE_STATUS CHAR(1) DEFAULT 'Y' NOT NULL,
	MEMO VARCHAR2(200),
	PRIMARY KEY (CATEGORY, CD)
);


CREATE TABLE URL_CODE_ERROR
(
	-- 코드표의 CATEGORY 그룹 참조
	CATEGORY VARCHAR2(20) NOT NULL,
	CD VARCHAR2(20) NOT NULL,
	CD_DESC VARCHAR2(100) NOT NULL,
	-- Y,N
	USE_STATUS CHAR(1) DEFAULT 'Y' NOT NULL,
	MEMO VARCHAR2(200),
	PRIMARY KEY (CATEGORY, CD)
);


CREATE TABLE URL_DB
(
	-- DB01, DB02, ... 
	DB_ID VARCHAR2(20) NOT NULL,
	-- DBG01, DBG02, ...
	DBGRP_ID VARCHAR2(20) NOT NULL,
	-- 로그인아이디
	USER_ID VARCHAR2(20),
	PWD VARCHAR2(20),
	-- Y,N
	USE_STATUS CHAR(1),
	DB_URL VARCHAR2(200),
	DB_DRIVER VARCHAR2(100),
	DB_TEST_SQL VARCHAR2(100),
	MEMO VARCHAR2(200),
	PRIMARY KEY (DB_ID)
);


CREATE TABLE URL_MSG_MAIN_YYYYMM
(
	-- 수신RS번호(2), 생성일자(14), 폴더정보(3+4:고유번호), DB아이디(2), 예약필드(5:테이블번호3+2)
	SVR_KEY CHAR(18) NOT NULL,
	-- Agent와 연동되는 아이디
	CLI_ID VARCHAR2(20) NOT NULL,
	BILL_ID VARCHAR2(20) NOT NULL,
	-- DB01, DB02, ... 
	DB_ID VARCHAR2(20),
	MW_URL VARCHAR2(20),
	-- Agent와 연동되는 키값
	CLI_KEY VARCHAR2(20) NOT NULL,
	NO_SND VARCHAR2(15),
	NO_CB VARCHAR2(15) NOT NULL,
	NO_RCV VARCHAR2(15) NOT NULL,
	-- 제목이 없는 경우, 본문에서 잘라서 넣는다. (11/06,yoyozo)
	SUBJECT VARCHAR2(60) NOT NULL,
	-- L(ms), M(ms), S(ms) 구분자
	SVC_TP CHAR(1) NOT NULL,
	DT_R_CLI VARCHAR2(14) NOT NULL,
	-- 에러 코드표 참조
	RSLT_M VARCHAR2(4),
	-- 에러코드표 참조
	RSLT_E VARCHAR2(4),
	PRIMARY KEY (SVR_KEY)
);


CREATE TABLE URL_MSG_YYYYMM
(
	-- 수신RS번호(2), 생성일자(14), 폴더정보(3+4:고유번호), DB아이디(2), 예약필드(5:테이블번호3+2)
	SVR_KEY CHAR(18) NOT NULL,
	URL_SEQ NUMBER NOT NULL,
	-- Agent와 연동되는 아이디
	CLI_ID VARCHAR2(20),
	-- Agent와 연동되는 키값
	CLI_KEY VARCHAR2(20) NOT NULL,
	BILL_ID VARCHAR2(20),
	NO_SND VARCHAR2(15),
	NO_RCV VARCHAR2(15) NOT NULL,
	NO_CB VARCHAR2(15) NOT NULL,
	-- 제목이 없는 경우, 본문에서 잘라서 넣는다. (11/06,yoyozo)
	SUBJECT VARCHAR2(60) NOT NULL,
	-- L(ms), M(ms), S(ms) 구분자
	SVC_TP CHAR(1) NOT NULL,
	-- LMS에서는 메시지 앞100바이트 저장
	MSG VARCHAR2(100) NOT NULL,
	MSG_LEN NUMBER,
	-- MMS에 사용되는 이미지수
	MMS_IMG_CNT NUMBER,
	-- Y, N
	EXC_YN CHAR(1) DEFAULT 'N',
	-- 특정문자열을 생성된 url로 변경해야 됨
	EXC_TEXT VARCHAR2(90),
	MW_URL VARCHAR2(20),
	PRICE NUMBER(10,2),
	TEL VARCHAR2(10),
	-- 폰정보서버에게 읽음
	PI_LCD VARCHAR2(20),
	PI_MODEL VARCHAR2(20),
	PI_TELCO VARCHAR2(10),
	-- Y, N
	EXCEPT_PHONE_STATUS CHAR(1) DEFAULT 'N',
	RS_ID VARCHAR2(20),
	TS_ID VARCHAR2(20),
	TEL_ID VARCHAR2(20),
	TEL_ID_E VARCHAR2(20),
	DT_R_CLI VARCHAR2(14) NOT NULL,
	DT_R_TS VARCHAR2(14),
	DT_S_PI VARCHAR2(14),
	DT_R_PI VARCHAR2(14),
	DT_S_TEL VARCHAR2(14),
	DT_P_TEL VARCHAR2(14),
	DT_R_DVC VARCHAR2(14),
	DT_R_TEL VARCHAR2(14),
	DT_S_RS VARCHAR2(14),
	DT_S_CLI VARCHAR2(14),
	DT_S_TEL_E VARCHAR2(14),
	DT_P_TEL_E VARCHAR2(14),
	DT_R_DVC_E VARCHAR2(14),
	DT_R_TEL_E VARCHAR2(14),
	DT_S_CLI_E VARCHAR2(14),
	SND_CNT NUMBER DEFAULT 0,
	-- 코드표 참조
	RS_STT VARCHAR2(20) NOT NULL,
	-- 에러 코드표 참조
	RSLT_M VARCHAR2(4),
	-- 에러코드표 참조
	RPT_RSLT VARCHAR2(4),
	DESC_M VARCHAR2(200),
	-- 코드표 참조
	RS_STT_E VARCHAR2(20),
	-- 에러코드표 참조
	RSLT_E VARCHAR2(4),
	-- 에러코드표 참조
	RPT_RSLT_E VARCHAR2(4),
	DESC_E VARCHAR2(200),
	CERT_SMS_CNT NUMBER,
	-- ETC3
	CERT_PRICE NUMBER(10,2),
	-- 클라이언트에서 발송한 시간
	DT_CLI VARCHAR2(14),
	-- 기타 클라이언트필드1
	CLI_ETC1 VARCHAR2(40),
	-- 기타 클라이언트필드2
	CLI_ETC2 VARCHAR2(40),
	PRIMARY KEY (SVR_KEY)
);


CREATE TABLE URL_MW_HTML
(
	-- * 기존 템플릿키라는 명칭으로도 사용됨
	HTML_KEY VARCHAR2(20) NOT NULL,
	-- Agent와 연동되는 아이디
	CLI_ID VARCHAR2(20),
	-- 코드표 참조
	-- 
	HTML_TYPE VARCHAR2(20) NOT NULL,
	-- 모바일웹 가변 텍스트 수
	MW_TEXT_CNT NUMBER,
	-- 모바일웹 가변이미지 수
	MW_IMAGE_CNT NUMBER,
	-- 쿠폰수
	COUPON_CNT NUMBER,
	-- 페이지 시작일
	DT_START VARCHAR2(14),
	-- 페이지 종료일
	DT_END VARCHAR2(14),
	-- 강제종료 시간
	DT_FORCE_END VARCHAR2(14),
	-- HTML 생성시간
	DT_CREATE VARCHAR2(14),
	-- HTML 수정시간
	DT_MODIFY VARCHAR2(14),
	-- SMS 본인인증 사용여부(Y|N)
	CERT_SMS_YN CHAR(0),
	CERT_USER_CNT NUMBER,
	PRIMARY KEY (HTML_KEY)
);


CREATE TABLE URL_MW_HTML_TAG
(
	SEQ NUMBER NOT NULL,
	-- * 기존 템플릿키라는 명칭으로도 사용됨
	HTML_KEY VARCHAR2(20) NOT NULL,
	-- 페이지번호
	PAGE_NUM NUMBER,
	-- 태그순번
	TAG_SEQ NUMBER,
	-- 태그이름
	TAG_KEY VARCHAR2(100),
	TAG_VALUE VARCHAR2(1000),
	PRIMARY KEY (SEQ)
);


CREATE TABLE URL_MW_INFO_YYYYMM
(
	-- 수신RS번호(2), 생성일자(14), 폴더정보(3+4:고유번호), DB아이디(2), 예약필드(5:테이블번호3+2)
	SVR_KEY CHAR(18) NOT NULL,
	BILL_ID VARCHAR2(20),
	NO_RCV VARCHAR2(15),
	-- 코드표 참조
	-- 
	HTML_TYPE VARCHAR2(20),
	-- * 기존 템플릿키라는 명칭으로도 사용됨
	HTML_KEY VARCHAR2(20),
	-- 최대 3개, '|'으로 구분
	COUP_NUM VARCHAR2(200),
	DT_CONN VARCHAR2(14),
	DT_EVNT1 VARCHAR2(14),
	DT_EVNT2 VARCHAR2(14),
	DT_EVNT3 VARCHAR2(14),
	EVNT_ANSWER1 VARCHAR2(200),
	EVNT_ANSWER2 VARCHAR2(200),
	EVNT_ANSWER3 VARCHAR2(200),
	DT_COUPON1 VARCHAR2(14),
	DT_COUPON2 VARCHAR2(14),
	DT_COUPON3 VARCHAR2(14),
	-- '|'으로 구분, Page 구분없음
	MW_TEXT VARCHAR2(1000),
	-- '|'으로 구분, Page 구분없음
	MW_IMAGE VARCHAR2(1000),
	-- 코드표 참조
	-- 1:사용안함, 2:휴대폰번호, 3:SMS인증번호, 4:직접입력
	CERT_TYPE1 CHAR(1) DEFAULT '1',
	CERT_USER_RES1 VARCHAR2(50),
	DT_CERT_REQ1 VARCHAR2(14),
	CERT_TYPE2 CHAR(1),
	CERT_USER_RES2 VARCHAR2(50),
	DT_CERT_REQ2 VARCHAR2(14),
	PRIMARY KEY (SVR_KEY)
);


-- 처리 후, 삭제
CREATE TABLE URL_MW_RPT
(
	SEQ NUMBER NOT NULL,
	-- 수신RS번호(2), 생성일자(14), 폴더정보(3+4:고유번호), DB아이디(2), 예약필드(5:테이블번호3+2)
	-- ETC1
	-- 
	SVR_KEY CHAR(18) NOT NULL,
	-- Agent와 연동되는 아이디
	CLI_ID VARCHAR2(20) NOT NULL,
	-- Agent와 연동되는 키값
	CLI_KEY VARCHAR2(20) NOT NULL,
	-- 코드표 참조
	-- 접속시간, 인증시간, 응모/조회 시간, 쿠폰사용시간
	-- ETC2
	RPT_TYPE VARCHAR2(20) NOT NULL,
	DT_RPT VARCHAR2(14),
	EVNT_NO CHAR(1),
	EVNT_ANSWER VARCHAR2(200),
	-- ETC3
	CERT_PRICE NUMBER(10,2),
	-- 1,2,3,4
	CERT_NO CHAR(1) DEFAULT '1',
	-- 코드표 참조
	-- 1000이면 성공, 그외 실패
	CERT_RSLT VARCHAR2(20),
	CERT_DESC VARCHAR2(200),
	MW_PID VARCHAR2(20),
	-- 클라이언트에서 발송한 시간
	DT_CLI VARCHAR2(14),
	-- 기타 클라이언트필드1
	CLI_ETC1 VARCHAR2(40),
	-- 기타 클라이언트필드2
	CLI_ETC2 VARCHAR2(40),
	DT_REG VARCHAR2(14) NOT NULL,
	-- 코드표 참조
	RS_STT VARCHAR2(20) NOT NULL,
	-- 에러 코드표 참조
	RSLT_M VARCHAR2(4),
	PRIMARY KEY (SEQ)
);


-- 처리 후, 삭제
CREATE TABLE URL_MW_RPT_LOG_YYYYMM
(
	SEQ NUMBER NOT NULL,
	-- 수신RS번호(2), 생성일자(14), 폴더정보(3+4:고유번호), DB아이디(2), 예약필드(5:테이블번호3+2)
	SVR_KEY CHAR(18) NOT NULL,
	-- Agent와 연동되는 키값
	CLI_KEY VARCHAR2(20) NOT NULL,
	-- 코드표 참조
	-- 접속시간, 인증시간, 응모/조회 시간, 쿠폰사용시간
	-- ETC2
	RPT_TYPE VARCHAR2(20) NOT NULL,
	DT_RPT VARCHAR2(14),
	-- ETC3
	CERT_PRICE NUMBER(10,2),
	-- 1,2,3,4
	CERT_NO CHAR(1) DEFAULT '1',
	-- 코드표 참조
	-- 1000이면 성공, 그외 실패
	CERT_RSLT VARCHAR2(20),
	CERT_DESC VARCHAR2(200),
	MW_PID VARCHAR2(20) NOT NULL,
	DT_REG VARCHAR2(14) NOT NULL,
	-- 에러 코드표 참조
	RSLT_M VARCHAR2(4),
	PRIMARY KEY (SEQ)
);


CREATE TABLE URL_STAT
(
	STAT_DAY VARCHAR2(8) NOT NULL,
	-- Agent와 연동되는 아이디
	CLI_ID VARCHAR2(20) NOT NULL,
	BILL_ID VARCHAR2(20) NOT NULL,
	-- L(ms), M(ms), S(ms) 구분자
	SVC_TP CHAR(1),
	SEND_CNT NUMBER,
	SUCC_CNT NUMBER,
	FAIL_CNT NUMBER,
	ERR_CNT NUMBER,
	ING_CNT NUMBER,
	EXC_SMS_CNT NUMBER,
	PRIMARY KEY (STAT_DAY, CLI_ID, BILL_ID)
);


CREATE TABLE URL_STAT_MW
(
	STAT_DAY VARCHAR2(8) NOT NULL,
	-- * 기존 템플릿키라는 명칭으로도 사용됨
	HTML_KEY VARCHAR2(20) NOT NULL,
	-- Agent와 연동되는 아이디
	CLI_ID VARCHAR2(20) NOT NULL,
	BILL_ID VARCHAR2(20) NOT NULL,
	CONN_CNT NUMBER,
	CERT_SUCC_CNT NUMBER,
	CERT_REQ_CNT_SMS NUMBER,
	EVNT_CNT NUMBER,
	COUP_CNT NUMBER,
	PRIMARY KEY (STAT_DAY, HTML_KEY, CLI_ID, BILL_ID)
);



/* Create Foreign Keys */

ALTER TABLE URL_MSG_MAIN_YYYYMM
	ADD FOREIGN KEY (CLI_ID, BILL_ID)
	REFERENCES URL_CLIENT (CLI_ID, BILL_ID)
;


ALTER TABLE URL_STAT
	ADD FOREIGN KEY (CLI_ID, BILL_ID)
	REFERENCES URL_CLIENT (CLI_ID, BILL_ID)
;


ALTER TABLE URL_STAT_MW
	ADD FOREIGN KEY (CLI_ID, BILL_ID)
	REFERENCES URL_CLIENT (CLI_ID, BILL_ID)
;


ALTER TABLE URL_MSG_YYYYMM
	ADD FOREIGN KEY (SVR_KEY)
	REFERENCES URL_MSG_MAIN_YYYYMM (SVR_KEY)
;


ALTER TABLE URL_MW_INFO_YYYYMM
	ADD FOREIGN KEY (SVR_KEY)
	REFERENCES URL_MSG_YYYYMM (SVR_KEY)
;


ALTER TABLE URL_MW_RPT_LOG_YYYYMM
	ADD FOREIGN KEY (SVR_KEY)
	REFERENCES URL_MSG_YYYYMM (SVR_KEY)
;


ALTER TABLE URL_MW_HTML_TAG
	ADD FOREIGN KEY (HTML_KEY)
	REFERENCES URL_MW_HTML (HTML_KEY)
;


ALTER TABLE URL_MW_RPT
	ADD FOREIGN KEY (SVR_KEY)
	REFERENCES URL_MW_INFO_YYYYMM (SVR_KEY)
;



